mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/',views.password, name="password"),
    path('follow/<int:user_pk>/',views.follow,name="follow"),
    #상단으로 가면 accounts뒤에오는 모든 문자열이 다 적용된다 그래서 맨 밑
    path('<str:username>/',views.profile,name="profile"), 

    

]

mysite/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/comment/',views.comment, name="comment"),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/',views.comment_delete,name="comment_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/recommend/', views.recommend, name="recommend"),
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

mysite/mysite/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://kit.fontawesome.com/f02ed41bdb.js" crossorigin="anonymous"></script>

  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  <div class="float-right" >
    
  </div><br>
  {% if messages %}
      {% for data in messages %} 
      <div class="row" style="margin:20px auto;">
      <div class="col-sm-12">
        <div class="alert alert-{{data.tags}}">
          <strong>{{data.tags}} </strong>{{data.message}}
        
        </div>
      </div>
      </div>        
      {% endfor %}
    {% endif %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'articles:index' %}">HOME</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if user.is_authenticated %}
          <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">로그아웃 <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'accounts:update' %}">회원수정</a>
          <a class="nav-item nav-link" href="{% url 'accounts:profile' user.username %}">회원정보</a>
          <a class="nav-item nav-link" href="{% url 'accounts:password' %}">비밀번호 수정</a>
          <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="회원 탈퇴">
          </form>
        {% else %}
          <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
          <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        {% endif %}
          
      </div>
    </div>
  </nav>
  

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>
</html>